### ISSUE TITLE
Are views a coroutines?

### ISSUE THREAD

**Issue by JerzySpendel** [pyGrowler/Growler#15]
Let's take a look at the documentation example:
```

from growler import App

app = App()

@app.use
def log_file(req, res):
    print("<{ip}> {req_path}".format(ip=req.ip, req_path=req.path))

@app.get("/")
def index_file(req, res):
    res.send_text("index.")

app.create_server_and_run_forever(host='0.0.0.0', port='8080')
```

Is `index_file` a coroutine from which I could do a `yield from`?

**Comment by akubera** [comment]
Growler accepts both normal functions and coroutine functions as middleware, and will handle each appropriately.

Just adorn the function with `@asyncio.coroutine` and you can `yield from` all you like.

[Example 2](https://github.com/pyGrowler/Growler/blob/0ef460a2799f1d4ec9978cb449680a5fc01725d5/examples/example2/__main__.py) demonstrates this.

Note, I'm going to drop py3.4 support with my next version (v0.9.x), and I recommend using `async` & `await` notation instead of asyncio.coroutine

**Comment by JerzySpendel** [comment]
Ok, super! :) I didn't find this example in documentation.
