### ISSUE TITLE
Implement ETag

### ISSUE THREAD

**Issue by akubera** [pyGrowler/Growler#5]
ETags are a core feature of web servers that users should expect to work out of the box. This should be a non-middleware feature baked into either [Application](https://github.com/pyGrowler/Growler/blob/dev/growler/application.py#L56) or [HTTPRequest](https://github.com/pyGrowler/Growler/blob/dev/growler/http/response.py#L19) classes, with the option to disable or swap implementations if the user so chooses.

**Comment by nudzo** [comment]
Get inspired: [https://github.com/mholt/caddy/issues/191](https://github.com/mholt/caddy/issues/191)

**Comment by akubera** [comment]
Thanks for your suggestion, @nudzo. Do you think it's best to just integrate etags into the [static middleware](https://github.com/pyGrowler/Growler/blob/dev/growler/middleware/static.py) vs some other, more general, mechanism?

**Comment by nudzo** [comment]
Yes, one I mentioned above is for static content.
Dynamic content best when generate ETags itself, cause it can do it the most effective way - based on version of doc, or hash generated on doc save, or similar. Otherwise you have to calculate some kind of hash on every response - performance impact.
