### ISSUE TITLE
GrowlerHTTPResponder' object has no attribute 'client_query'

### ISSUE THREAD

**Issue by leonardoo** [pyGrowler/Growler#9]
when i try to get get a param from a url, the app gave me this error

ERROR:growler.router:4441216280:'GrowlerHTTPResponder' object has no attribute 'client_query'
ERROR:growler.middleware_chain:4437457384:'GrowlerHTTPResponder' object has no attribute 'client_query'
https://gist.github.com/leonardoo/cc9c0ae4ac0593553b4bfea239758528

the fix is change:

```python
....
    @property
    def query(self):
        return self._protocol.client_query
```

for this:

```python
....
    @property
    def query(self):
        return self._protocol.parsed_query
```

**Comment by akubera** [comment]
Thanks for your contribution! That bug was introduced a while ago when I was trying to move away from the parser storing data and putting more client information into the Protocol object. The target for that particular property was [this attribute](https://github.com/pyGrowler/Growler/blob/dev/growler/http/protocol.py#L33) (otherwise unused). This also shows I need to buckle down and get more test coverage.
